version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./models:/app/models  
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/model.pkl
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    driver: bridge