name: Mlops_predictive

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Prepare Environment
        run: |
          #your ml worflow goes here 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python script.py


      - name: Install dependencies
        run: |
          npm install

      f

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm run deploy